name: Publish
on:
  push:
    tags: '*'

jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Publish
          env:
            APIKEY: ${{ secrets.PSGALLERYAPIKEY }}
          run: .\publish.ps1
          shell: pwsh
